---

- name: Copy error pages
  copy:
    src: files/errors
    dest: "{{ openresty_root_dir }}"
    mode: 0644

- name: Copy ssl certificates
  copy:
    content: "{{ item.value.certificate_value }}"
    dest: "{{ item.value.certificate }}"
    mode: 0640
  with_dict: "{{ openresty_ssl_files }}"

- name: Copy ssl keys
  copy:
    content: "{{ item.value.key_value }}"
    dest: "{{ item.value.key }}"
    mode: 0400
  with_dict: "{{ openresty_ssl_files }}"

- name: Copy mime.types file
  copy:
    src: files/mime.types
    dest: "{{ openresty_conf_dir }}/mime.types"
    mode: 0644
  notify:
    - reload nginx

- name: Configure nginx params files
  template:
    src: openresty/nginx.params.j2
    dest: "{{ openresty_conf_dir }}/{{ item.filename }}"
    mode: 0644
  notify:
    - reload nginx
  with_items:
    - "{{ openresty_params }}"
    - "{{ openresty_lua_params }}"
    - "{{ openresty_addtional_params }}"

- name: Configure nginx sites files
  template:
    src: openresty/conf.d/site.conf.j2
    dest: "{{ openresty_confd_dir }}/{{ item.filename }}.conf"
    mode: 0644
  notify:
    - reload nginx
  with_items:
    - "{{ openresty_default_sites_conf }}"
    - "{{ openresty_lua_default_sites_conf }}"
    - "{{ openresty_sites_conf }}"
  register: template_results

- name: Set nginx managed sites
  set_fact:
    managed_files: "{{ template_results.results|selectattr('invocation', 'defined')|map(attribute='invocation.module_args.dest')|list }}"

- name: Check all conf files in "{{ openresty_confd_dir }}"
  find:
    paths: "{{ openresty_confd_dir }}"
    patterns: "*.conf"
  register: all_files

- name: Set unmanaged files in "{{ openresty_confd_dir }}"
  set_fact:
    files_to_delete: "{{ all_files.files | map(attribute='path') | difference(managed_files) }}"

- name: Delete unmanaged files in "{{ openresty_confd_dir }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ files_to_delete }}"
  when: openresty_conf_cleanup_unused_files

- name: Configure nginx.conf
  template:
    src: openresty/nginx.conf.j2
    dest:  "{{ openresty_conf_dir }}/nginx.conf"
    mode: 0644
    #validate: "{{ openresty_server_pkg }} -c %s -t"
  notify:
    - reload nginx

- name: Generate dh group
  command: "openssl dhparam -out {{ openresty_ssl_dhparam_file }} {{ openresty_ssl_dhparam_size }}"
  args:
    creates: "{{ openresty_ssl_dhparam_file }}"
  notify:
    - reload nginx

- name: Create Openresty systemd service
  include_role:
    name: ansible.systemd-service
  vars:
    systemd_service: "{{ openresty_systemd_service }}"
    systemd_service_path: "{{ openresty_systemd_service_path }}"

- name: Configure logrotate.d/openresty
  template:
    src: logrotate.d/openresty.j2
    dest:  "{{ openresty_logrotate_dir }}/openresty"
    mode: 0644
  when: openresty_logrotate_enabled
